FROM golang:1.27-alpine
ARG VERSION=RELEASE.2025-10-15T17-29-55Z

ENV CGO_ENABLED=0
RUN apk add --no-cache git
RUN git clone -b ${VERSION} https://github.com/minio/minio.git
RUN cd minio && go build -trimpath -ldflags "$(go run buildscripts/gen-ldflags.go)" -o /minio main.go
RUN cd minio && rm -rf .git && tar -czf /minio.tar.gz .

FROM alpine:latest
COPY --from=0 /minio.tar.gz /minio.tar.gz
COPY --from=0 /minio /usr/local/bin/minio
COPY --from=0 /go/minio/dockerscripts/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]